version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: repsy-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repsydb
    ports:
      - "5432:5432"
    networks:
      - repsy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  repsy-api:
    build: .
    container_name: repsy-repo-api
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/repsydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - repsy-network

networks:
  repsy-network:
    driver: bridge
